name: Go

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Build
      run: go build
      
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
        release_branches: master
        custom_release_rules: |
          release:major,
          bug:patch,
          fix:patch,
          feature:minor
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: ${{ steps.tag_version.outputs.changelog }}
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        name: Scabiosa ${{ steps.tag_version.outputs.new_tag }}
        draft: false
        prerelease: false
        files: |
          scabiosa
